#! /bin/bash

script_file=$(readlink -f $0)
script_dir=$(dirname "$script_file")
shell=$(basename "$SHELL")

if [ "$shell" = "zsh" ]; then
  echo -e "\n#THIS MUST BE AT THE END OF THE FILE FOR DEVENV TO WORK!!!" >> "$HOME/.zshrc"
  echo "source $script_dir/.devenvrc" >> "$HOME/.zshrc"
else
  echo -e "\n#THIS MUST BE AT THE END OF THE FILE FOR DEVENV TO WORK!!!" >> "$HOME/.bashrc"
  echo "source $script_dir/.devenvrc" >> "$HOME/.bashrc"
fi

exec $SHELL -l;