#! /bin/bash

script_file=$(readlink -f $0)
script_dir=$(dirname "$SCRIPT")
export PATH=$PATH:$script_dir/bin
echo -e "\n#THIS MUST BE AT THE END OF THE FILE FOR DEVENV TO WORK!!!\nsource $script_dir/.devenv.bashrc" >> "$HOME/.bashrc"
exec $SHELL -l;